/* documents-runtime.js — Engine 25.7.1 Trip Documents v1
   Trip-wide utility attachments: upload, pin and contextual links. */
(function(root){'use strict';
const cfg=root.SYNC_CONFIG||{}, store=root.STORAGE?.local;
const KEY='travel_engine_documents_v1', table=cfg.tables?.documents||'trip_documents', bucket=cfg.storage?.documentsBucket||'trip-documents';
const seed=[{id:'doc-edgewater-first-table-20260924',title:'Edgewater Restaurant · First Table Voucher',category:'Bookings & vouchers',note:'24 Sep · 5:00 PM · 50% off food for four people · mention First Table on arrival.',fileName:'Edgewater-First-Table-JL8DQZ.pdf',mimeType:'application/pdf',fileUrl:'documents/Edgewater-First-Table-JL8DQZ.pdf',pinned:true,linkType:'guide',linkId:'edgewater-restaurant',linkLabel:'Edgewater Restaurant',createdAt:'2026-09-19T00:00:00.000Z',updatedAt:'2026-09-19T00:00:00.000Z',seeded:true}];
function uuid(){return root.crypto?.randomUUID?root.crypto.randomUUID():'doc-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function read(){let x=[];try{x=store?.readJSON?store.readJSON(KEY,[]):JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){};if(!Array.isArray(x))x=[];const ids=new Set(x.map(d=>d.id));seed.forEach(d=>{if(!ids.has(d.id))x.push(d)});return x.sort((a,b)=>(!!b.pinned-!!a.pinned)||String(b.updatedAt).localeCompare(String(a.updatedAt)))}
function write(x){if(store?.writeJSON)store.writeJSON(KEY,x);else localStorage.setItem(KEY,JSON.stringify(x));document.dispatchEvent(new CustomEvent('travelengine:documentschanged'))}
function configured(){return !!(cfg.enabled&&cfg.url&&cfg.anonKey&&root.SUPABASE?.isConfigured?.())}
async function cloudUpload(doc,file){if(!configured()||!navigator.onLine)return doc;await root.SUPABASE.getSession();const c=root.SUPABASE.getClient();const safe=(file.name||'document').replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${cfg.tripId}/${doc.id}/${safe}`;const up=await c.storage.from(bucket).upload(path,file,{upsert:true,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const pub=c.storage.from(bucket).getPublicUrl(path).data?.publicUrl;doc.fileUrl=pub||doc.fileUrl;doc.filePath=path;const row={id:doc.id,trip_id:cfg.tripId,payload:doc,created_at:doc.createdAt,updated_at:doc.updatedAt};const q=await c.from(table).upsert(row,{onConflict:'id'});if(q.error)throw q.error;return doc}
async function add(meta,file){const now=new Date().toISOString(),doc={id:uuid(),title:meta.title||file?.name||'Document',category:meta.category||'Other',note:meta.note||'',pinned:!!meta.pinned,linkType:meta.linkType||'trip',linkId:meta.linkId||'',linkLabel:meta.linkLabel||'Trip-wide',fileName:file?.name||'',mimeType:file?.type||'',createdAt:now,updatedAt:now};if(file){const url=URL.createObjectURL(file);doc.localObjectUrl=url;try{await cloudUpload(doc,file)}catch(e){doc.uploadPending=true;doc.uploadError=e.message||String(e)}}const list=read().filter(x=>x.id!==doc.id);list.push(doc);write(list);return doc}
async function sync(){if(!configured()||!navigator.onLine)return read();try{await root.SUPABASE.getSession();const c=root.SUPABASE.getClient();const q=await c.from(table).select('payload').eq('trip_id',cfg.tripId);if(q.error)throw q.error;const local=read(), map=new Map(local.map(x=>[x.id,x]));(q.data||[]).forEach(r=>{const d=r.payload;if(d?.id&&!d.seeded)map.set(d.id,d)});const out=[...map.values()];write(out);return out}catch(e){return read()}}
function update(id,patch){const list=read(),i=list.findIndex(x=>x.id===id);if(i<0)return;list[i]=Object.assign({},list[i],patch,{updatedAt:new Date().toISOString()});write(list);if(configured()&&navigator.onLine&&!list[i].seeded){root.SUPABASE.getSession().then(()=>root.SUPABASE.getClient().from(table).upsert({id:list[i].id,trip_id:cfg.tripId,payload:list[i],created_at:list[i].createdAt,updated_at:list[i].updatedAt},{onConflict:'id'})).catch(()=>{})}}
function remove(id){const d=read().find(x=>x.id===id);if(d?.seeded)return false;write(read().filter(x=>x.id!==id));if(configured()&&navigator.onLine)root.SUPABASE.getSession().then(()=>root.SUPABASE.getClient().from(table).delete().eq('id',id).eq('trip_id',cfg.tripId)).catch(()=>{});return true}
root.TRIP_DOCUMENTS=Object.freeze({read,add,sync,update,remove});
})(globalThis);
