(function(root){'use strict';
const $=id=>document.getElementById(id);function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function targets(){const out=[['trip','','Trip-wide']];for(let i=1;i<=10;i++)out.push(['day',String(i),`Day ${i}`]);Object.values(root.TRAVEL_DATASETS?.BOOKINGS_DATA||{}).forEach(b=>out.push(['booking',b.id,b.title]));Object.entries(root.TRAVEL_DATASETS?.PLACES||{}).forEach(([id,p])=>out.push(['guide',id,p.title]));return out}
function renderTargets(){const s=$('docLink');if(!s)return;s.innerHTML=targets().map(x=>`<option value="${esc(x[0]+'|'+x[1])}">${esc(x[2])}</option>`).join('')}
function linkHref(d){if(d.linkType==='day')return`day.html?day=${encodeURIComponent(d.linkId)}`;if(d.linkType==='booking')return`trip.html?booking=${encodeURIComponent(d.linkId)}`;if(d.linkType==='guide')return`place.html?placeId=${encodeURIComponent(d.linkId)}`;return'index.html'}
function render(){const list=root.TRIP_DOCUMENTS.read(), box=$('documentsList');$('docCount').textContent=`${list.length} ${list.length===1?'document':'documents'}`;box.innerHTML=list.map(d=>`<article class="doc-card ${d.pinned?'is-pinned':''}"><div class="doc-top"><span class="doc-icon">${d.mimeType?.startsWith('image/')?'🖼️':d.mimeType?.includes('pdf')?'📄':'📎'}</span><div><small>${esc(d.category||'Other')}</small><h3>${esc(d.title)}</h3></div><button class="pin-btn" onclick="togglePin('${esc(d.id)}')" aria-label="${d.pinned?'Unpin':'Pin'}">${d.pinned?'📌':'📍'}</button></div>${d.note?`<p>${esc(d.note)}</p>`:''}<div class="doc-meta">${d.fileName?esc(d.fileName):'Attachment'}${d.uploadPending?' · Saved on this device':''}</div><div class="doc-actions"><a class="pill" href="${esc(d.fileUrl||d.localObjectUrl||'#')}" ${d.fileUrl||d.localObjectUrl?'target="_blank" rel="noopener"':''}>Open</a><a class="pill" href="${linkHref(d)}">🔗 ${esc(d.linkLabel||'Trip')}</a>${d.seeded?'':`<button class="pill danger" onclick="deleteDoc('${esc(d.id)}')">Delete</button>`}</div></article>`).join('')||'<div class="empty-state">No documents yet.</div>'}
root.togglePin=id=>{const d=root.TRIP_DOCUMENTS.read().find(x=>x.id===id);if(d)root.TRIP_DOCUMENTS.update(id,{pinned:!d.pinned});render()};root.deleteDoc=id=>{if(confirm('Delete this document?')){root.TRIP_DOCUMENTS.remove(id);render()}};
root.openAddDocument=()=>{$('docModal').classList.add('show')};root.closeAddDocument=()=>{$('docModal').classList.remove('show')};
root.saveDocument=async()=>{const file=$('docFile').files[0];if(!file){alert('Choose a photo, PDF or Word document.');return}const title=$('docTitle').value.trim()||file.name;const [linkType,linkId]=$('docLink').value.split('|');const label=$('docLink').selectedOptions[0]?.textContent||'Trip-wide';$('docSave').disabled=true;$('docSave').textContent='Saving…';await root.TRIP_DOCUMENTS.add({title,category:$('docCategory').value,note:$('docNote').value.trim(),pinned:$('docPin').checked,linkType,linkId,linkLabel:label},file);$('docSave').disabled=false;$('docSave').textContent='Save Document';$('docForm').reset();closeAddDocument();render()};
document.addEventListener('DOMContentLoaded',()=>{renderTargets();render();root.TRIP_DOCUMENTS.sync().then(render)});document.addEventListener('travelengine:documentschanged',render);
})(globalThis);
