(function(root){'use strict';
const $=id=>document.getElementById(id);function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function targets(){const out=[['trip','','Trip-wide']];for(let i=1;i<=10;i++)out.push(['day',String(i),`Day ${i}`]);Object.values(root.TRAVEL_DATASETS?.BOOKINGS_DATA||{}).forEach(b=>out.push(['booking',b.id,b.title]));Object.entries(root.TRAVEL_DATASETS?.PLACES||{}).forEach(([id,p])=>out.push(['guide',id,p.title]));return out}
function renderTargets(){const s=$('docLink');if(!s)return;s.innerHTML=targets().map(x=>`<option value="${esc(x[0]+'|'+x[1])}">${esc(x[2])}</option>`).join('')}
function linkHref(d){if(d.linkType==='day')return`day.html?day=${encodeURIComponent(d.linkId)}`;if(d.linkType==='booking')return`trip.html?booking=${encodeURIComponent(d.linkId)}`;if(d.linkType==='guide')return`place.html?id=${encodeURIComponent(d.linkId)}`;return'index.html'}
function render(){const list=root.TRIP_DOCUMENTS.read(), box=$('documentsList');$('docCount').textContent=`${list.length} ${list.length===1?'document':'documents'}`;box.innerHTML=list.map(d=>`<article class="doc-card ${d.pinned?'is-pinned':''}"><div class="doc-top"><span class="doc-icon">${d.mimeType?.startsWith('image/')?'🖼️':d.mimeType?.includes('pdf')?'📄':'📎'}</span><div><small>${esc(d.category||'Other')}</small><h3>${esc(d.title)}</h3></div><button class="pin-btn" onclick="togglePin('${esc(d.id)}')" aria-label="${d.pinned?'Unpin':'Pin'}">${d.pinned?'📌':'📍'}</button></div>${d.note?`<p>${esc(d.note)}</p>`:''}<div class="doc-meta">${d.fileName?esc(d.fileName):'Attachment'}${d.uploadPending?' · Saved on this device':''}</div><div class="doc-actions"><button class="pill" onclick="openDocumentViewer('${esc(d.id)}')">📄 Open document</button>${d.seeded?'':`<button class="pill danger" onclick="deleteDoc('${esc(d.id)}')">Delete</button>`}</div></article>`).join('')||'<div class="empty-state">No documents yet.</div>'}
root.togglePin=id=>{const d=root.TRIP_DOCUMENTS.read().find(x=>x.id===id);if(d)root.TRIP_DOCUMENTS.update(id,{pinned:!d.pinned});render()};root.deleteDoc=id=>{if(confirm('Delete this document?')){root.TRIP_DOCUMENTS.remove(id);render()}};

async function renderPdfInto(url,wrap){wrap.innerHTML='<div class="doc-viewer-message">Loading document…</div>';try{if(!root.pdfjsLib)throw new Error('PDF viewer unavailable');root.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';const pdf=await root.pdfjsLib.getDocument(url).promise;wrap.innerHTML='';for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const base=page.getViewport({scale:1});const max=Math.min(900,Math.max(280,wrap.clientWidth-24));const scale=Math.min(2,max/base.width);const vp=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.className='pdf-page';canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);wrap.appendChild(canvas);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise}}catch(e){wrap.innerHTML='<div class="doc-viewer-message"><strong>Could not preview this document.</strong><p>Try again while online.</p></div>'}}
root.openDocumentViewer=id=>{const d=root.TRIP_DOCUMENTS.read().find(x=>x.id===id);if(!d)return;let url=d.fileUrl||d.localObjectUrl||'';if(d.embeddedBase64){try{const raw=atob(d.embeddedBase64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);url=URL.createObjectURL(new Blob([bytes],{type:d.mimeType||'application/pdf'}));}catch(e){}}$('docViewerTitle').textContent=d.title||'Document';const body=$('docViewerBody');body.innerHTML='';if(!url){body.innerHTML='<div class="doc-viewer-message">This document is not available on this device yet.</div>'}else if((d.mimeType||'').startsWith('image/')){const img=document.createElement('img');img.src=url;img.alt=d.title||'Document';body.appendChild(img)}else if((d.mimeType||'').includes('pdf')||/\.pdf(?:$|\?)/i.test(url)){const wrap=document.createElement('div');wrap.className='pdf-pages';body.appendChild(wrap);renderPdfInto(url,wrap)}else{const wrap=document.createElement('div');wrap.className='doc-viewer-message';wrap.innerHTML='<strong>'+esc(d.fileName||d.title||'Document')+'</strong><p>This file type opens in its native viewer.</p><a class="pill" target="_blank" rel="noopener">Open original file</a>';wrap.querySelector('a').href=url;body.appendChild(wrap)}$('docViewer').classList.add('show');$('docViewer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
root.closeDocumentViewer=()=>{$('docViewer').classList.remove('show');$('docViewer').setAttribute('aria-hidden','true');$('docViewerBody').innerHTML='';document.body.style.overflow=''};

root.openAddDocument=()=>{$('docModal').classList.add('show')};root.closeAddDocument=()=>{$('docModal').classList.remove('show')};
root.saveDocument=async()=>{const file=$('docFile').files[0];if(!file){alert('Choose a photo, PDF or Word document.');return}const title=$('docTitle').value.trim()||file.name;const [linkType,linkId]=$('docLink').value.split('|');const label=$('docLink').selectedOptions[0]?.textContent||'Trip-wide';$('docSave').disabled=true;$('docSave').textContent='Saving…';await root.TRIP_DOCUMENTS.add({title,category:$('docCategory').value,note:$('docNote').value.trim(),pinned:$('docPin').checked,linkType,linkId,linkLabel:label},file);$('docSave').disabled=false;$('docSave').textContent='Save Document';$('docForm').reset();closeAddDocument();render()};
document.addEventListener('DOMContentLoaded',()=>{renderTargets();render();root.TRIP_DOCUMENTS.sync().then(render)});document.addEventListener('travelengine:documentschanged',render);
})(globalThis);
