const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=__dirname;
const admin=fs.readFileSync(root+'/admin.js','utf8');
const data=fs.readFileSync(root+'/data.js','utf8');
assert(admin.includes('tripStudioSelectorToggle'), 'Studio toggle missing from selector');
assert(admin.includes("if(typeof window.openFriendModal==='function') window.openFriendModal();"), 'PIN success must reopen selector');
assert(!admin.includes('Manage itinerary, exports and trip data</small></span><span aria-hidden="true">›</span>'), 'Old nested Studio entry remains');
const ctx={};vm.createContext(ctx);vm.runInContext(data+';globalThis.__x={PLACES,CATEGORIES,GUIDE_ORDER};',ctx);
assert(ctx.__x.CATEGORIES.DINING.some(x=>x.key==='stoaker-room'),'Stoaker missing from Dining guide list');
assert(ctx.__x.GUIDE_ORDER.includes('stoaker-room'),'Stoaker missing from guide order');
assert(/barrel/i.test(ctx.__x.PLACES['stoaker-room'].desc),'Stoaker Why Go does not explain barrel cooking');
console.log('Stage 3.2H regression: 6/6 PASS');
