-- NZ Companion Stage 9A-1 — Supabase foundation
-- Run in Supabase SQL Editor. This creates a read-only published snapshot table.

create table if not exists public.trip_publications (
  id bigint generated by default as identity primary key,
  trip_id text not null,
  schema_version integer not null default 1,
  version integer not null,
  published_at timestamptz not null default now(),
  published_by text,
  payload jsonb not null,
  unique (trip_id, schema_version, version)
);

create index if not exists trip_publications_latest_idx
  on public.trip_publications (trip_id, schema_version, version desc);

alter table public.trip_publications enable row level security;

-- Anonymous users may read only published snapshots for the configured trip.
drop policy if exists "public can read trip publications" on public.trip_publications;
create policy "public can read trip publications"
  on public.trip_publications for select
  to anon
  using (trip_id = 'nz-family-2026');

-- No anonymous insert/update/delete policy is created.
-- Publishing remains unavailable until a later authenticated Admin stage.
