/* trip-config.js — Saigon Companion RC23 on Travel Engine 25.4.9 */
(function(root){'use strict';
const partyIdentities=Object.freeze({"party-christal": {"partyId": "party-christal", "emoji": "🧸", "displayName": "Christal", "legacyAliases": ["christal"], "ordering": 1, "permissions": {"adminEligible": false}}, "party-crystal": {"partyId": "party-crystal", "emoji": "👓", "displayName": "Crystal", "legacyAliases": ["crystal"], "ordering": 2, "permissions": {"adminEligible": true}}, "party-mero": {"partyId": "party-mero", "emoji": "✝️", "displayName": "Mero", "legacyAliases": ["mero"], "ordering": 3, "permissions": {"adminEligible": false}}, "party-vivian": {"partyId": "party-vivian", "emoji": "👟", "displayName": "Vivian", "legacyAliases": ["vivian"], "ordering": 4, "permissions": {"adminEligible": false}}});
const config=Object.freeze({
 id:'ccmv-vietnam-2026',tripName:'Saigon Companion',name:'Saigon Companion',destination:'Ho Chi Minh City',country:'Vietnam',startDate:'2026-10-30',endDate:'2026-11-03',currency:root.LOCALE_CONFIG.currency,timeZone:root.LOCALE_CONFIG.timeZone,language:root.LOCALE_CONFIG.language,
 logo:Object.freeze({splash:root.ASSET_CONFIG.branding.splashLogo,header:root.ASSET_CONFIG.branding.secondaryMark,icon192:root.ASSET_CONFIG.icons.icon192,icon512:root.ASSET_CONFIG.icons.icon512}),coverImage:root.ASSET_CONFIG.hero.coverImage,themeName:root.THEME_CONFIG.name,
 engineName:'Travel Engine',shortName:'Saigon',navLabel:'Saigon Companion',familyLabel:'CRYSTAL · CHRISTAL · VIVIAN · MERO',
 participants:Object.freeze({"presentation":"emoji-name","defaultKey": "crystal", "order": ["christal", "crystal", "mero", "vivian"], "identities": {"christal": {"emoji": "🧸", "code": "CHR", "name": "Christal"}, "crystal": {"emoji": "👓", "code": "CRY", "name": "Crystal"}, "mero": {"emoji": "✝️", "code": "MER", "name": "Mero"}, "vivian": {"emoji": "👟", "code": "VIV", "name": "Vivian"}}}),
 parties:Object.freeze({defaultPartyId:'party-crystal',order:Object.freeze(['party-christal','party-crystal','party-mero','party-vivian']),identities:partyIdentities}),
 admin:Object.freeze({user:'crystal',displayName:'Crystal',studioMessage:'Trip Studio is PIN protected. Enter the Studio PIN to continue.',completeMessage:'Complete this trip? Trip content remains available to browse, but Studio editing will be disabled until Crystal reopens the trip.',pin:'260922'}),
 tripModules:Object.freeze({stay:true,activities:true,transport:true,rentalCar:false}),
 tripMenuGroups:Object.freeze([Object.freeze({id:'activities-transport',title:'Activities & Transport',icon:'🎟️',sub:'Activity & transfer bookings',modules:Object.freeze(['activities','transport'])})]),
 bookingManagement:Object.freeze({mode:'collaborative',sync:Object.freeze({enabled:true,accessToken:'ccmv_vn_2026_7LxA9rPqK2mN8VfH5tYwQ3eUzC1JsBdR',pollIntervalMs:15000})}),
 home:Object.freeze({ariaLabel:'Saigon Companion home',reunionStory:'Four friends. Five days. One Saigon.',dateLine:'30 Oct — 3 Nov 2026',regionLine:'Ho Chi Minh City',clockLabel:'Saigon',homeCities:'Melbourne',clockSuffix:'VN',seasonLabel:'Girls trip',seasonNote:'Warm · humid · city days',welcomeMessage:'Welcome to Saigon',completedMessage:'Thanks for the moments'}),
 guide:Object.freeze({excludedPlaceIds:Object.freeze([]),worthExcludedPlaceIds:Object.freeze([]),categoryOrder:Object.freeze(['ATTRACTIONS','DINING','SHOP','STAY','WELLNESS']),categoryLabels:Object.freeze({ATTRACTIONS:'ATTRACTIONS',DINING:'DINING',SHOP:'SHOPPING',STAY:'STAY',WELLNESS:'WELLNESS'}),categoryMap:Object.freeze({ATTRACTIONS:Object.freeze(['ATTRACTIONS']),WELLNESS:Object.freeze(['SPA','WELLNESS']),DINING:Object.freeze(['DINING','RESTAURANTS','CAFÉS']),STAY:Object.freeze(['STAY']),SHOP:Object.freeze(['SHOP']),PRACTICAL:Object.freeze(['PRACTICAL'])})}),exports:Object.freeze({expenseSummaryTitle:'SAIGON EXPENSE SUMMARY'}),heroLine1:'Saigon',heroEmphasis:'Companion',tagline:'Eat · Shop · Spa · Explore',splashSlogan:'TRAVEL TOGETHER, CAPTURE TOGETHER',splashDestination:'VIETNAM 2026',storageNamespace:'ccmv-vietnam-2026',identityStorageKey:'ccmv-vietnam-2026:traveller_identity:v1',tripGeneration:1,bookingMasterRevision:7,version:'RC29.40-25.6.2',buildLabel:'Saigon Companion RC29.37 · Travel Engine 25.5.2',theme:root.THEME_CONFIG.colors
});root.TRIP_CONFIG=config;
function applyTripIdentity(){if(typeof document==='undefined')return;document.documentElement.lang=config.language;document.querySelectorAll('[data-trip-page-title]').forEach(el=>{const p=el.getAttribute('data-trip-page-title');document.title=p?p+' · '+config.tripName:config.tripName;});document.querySelectorAll('[data-brand-text]').forEach(el=>{const k=el.getAttribute('data-brand-text'),v=config[k];if(v==null)return;if(k==='splashSlogan')el.innerHTML=String(v).replace(/\n/g,'<br>');else el.textContent=v;});document.querySelectorAll('[data-brand-logo]').forEach(img=>{const k=img.getAttribute('data-brand-logo');if(config.logo[k])img.src=config.logo[k];});document.querySelectorAll('[data-trip-icon]').forEach(link=>{const k=link.getAttribute('data-trip-icon');if(config.logo[k])link.href=config.logo[k];});document.querySelectorAll('[data-trip-apple-title]').forEach(meta=>meta.content=config.destination);document.querySelectorAll('[data-trip-theme-color]').forEach(meta=>meta.content=config.theme.primary);document.querySelectorAll('[data-trip-currency-placeholder]').forEach(input=>input.placeholder='Total '+root.LOCALE_CONFIG.currency.code);document.querySelectorAll('[data-locale-currency-placeholder]').forEach(input=>input.placeholder='0.00 '+root.LOCALE_CONFIG.currency.code);}
root.applyTripIdentity=applyTripIdentity;if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyTripIdentity);else applyTripIdentity();}
})(globalThis);
